# Kubenix module for rerun-operator.
#
# Usage in nixlab/modules/k8s/...:
#   imports = [
#     inputs.rerun-operator.kubenixModules.rerun-operator
#   ];
#
#   rerun-operator = {
#     enable = true;
#     namespace = "rerun-operator";
#     image = "us-west1-docker.pkg.dev/casazza-identity/nixlab/rerun-operator:latest";
#   };
#
# The module emits:
#   - Namespace (optional, guarded by createNamespace)
#   - ServiceAccount
#   - ClusterRole / ClusterRoleBinding (watches RerunDashboard CRs cluster-wide,
#     CRUDs downstream Deployments / Services / ConfigMaps / PVCs)
#   - Deployment running `rerun-operator`
#   - Service exposing metrics + healthz on :8080
#   - CRD: rerundashboards.rerun.nixlab.io (minimal shell — real schema should
#     be generated by `rerun-operator export-crds` in a follow-up)
{
  config,
  lib,
  ...
}:
let
  cfg = config.rerun-operator;

  labels = {
    "app.kubernetes.io/name" = "rerun-operator";
    "app.kubernetes.io/managed-by" = "kubenix";
  };

  # Minimal CRD shell. The operator's Rust API (v1alpha1.rs) is the source of
  # truth; the production CRD should come from `rerun-operator export-crds`.
  # We keep spec+status as x-kubernetes-preserve-unknown-fields so any shape
  # validates at the apiserver and the operator does full validation at
  # reconcile time.
  # TODO: replace with the output of `rerun-operator export-crds` once the
  #       binary is released and `kubectl apply -f` can load it verbatim.
  rerunDashboardCrd = {
    apiVersion = "apiextensions.k8s.io/v1";
    kind = "CustomResourceDefinition";
    metadata = {
      name = "rerundashboards.rerun.nixlab.io";
      inherit labels;
    };
    spec = {
      group = "rerun.nixlab.io";
      scope = "Namespaced";
      names = {
        kind = "RerunDashboard";
        listKind = "RerunDashboardList";
        plural = "rerundashboards";
        singular = "rerundashboard";
        shortNames = [ "rrd" ];
      };
      versions = [
        {
          name = "v1alpha1";
          served = true;
          storage = true;
          subresources.status = { };
          additionalPrinterColumns = [
            {
              name = "Phase";
              type = "string";
              jsonPath = ".status.phase";
            }
            {
              name = "Web";
              type = "string";
              jsonPath = ".status.endpoints.web";
            }
            {
              name = "Loggers";
              type = "integer";
              jsonPath = ".status.connectedLoggers";
            }
            {
              name = "Visibility";
              type = "string";
              jsonPath = ".spec.presentation.ingress.visibility";
            }
            {
              name = "Age";
              type = "date";
              jsonPath = ".metadata.creationTimestamp";
            }
          ];
          schema.openAPIV3Schema = {
            type = "object";
            properties = {
              spec = {
                type = "object";
                "x-kubernetes-preserve-unknown-fields" = true;
              };
              status = {
                type = "object";
                "x-kubernetes-preserve-unknown-fields" = true;
              };
            };
          };
        }
      ];
    };
  };

  # ClusterRole rules. The operator watches RerunDashboard CRs cluster-wide
  # and creates downstream workload objects in the CR's own namespace.
  clusterRoleRules = [
    # RerunDashboard CRs (watch + patch status)
    {
      apiGroups = [ "rerun.nixlab.io" ];
      resources = [ "rerundashboards" ];
      verbs = [
        "get"
        "list"
        "watch"
        "patch"
        "update"
      ];
    }
    {
      apiGroups = [ "rerun.nixlab.io" ];
      resources = [ "rerundashboards/status" ];
      verbs = [
        "get"
        "patch"
        "update"
      ];
    }
    {
      apiGroups = [ "rerun.nixlab.io" ];
      resources = [ "rerundashboards/finalizers" ];
      verbs = [ "update" ];
    }

    # Downstream workload objects — full CRUD in whatever namespace the CR
    # lives in. RBAC is cluster-scoped because the CR can be in any namespace.
    {
      apiGroups = [ "apps" ];
      resources = [ "deployments" ];
      verbs = [
        "get"
        "list"
        "watch"
        "create"
        "update"
        "patch"
        "delete"
      ];
    }
    {
      apiGroups = [ "" ];
      resources = [
        "services"
        "configmaps"
        "persistentvolumeclaims"
      ];
      verbs = [
        "get"
        "list"
        "watch"
        "create"
        "update"
        "patch"
        "delete"
      ];
    }

    # Event emission for the CR — standard operator hygiene.
    {
      apiGroups = [ "" ];
      resources = [ "events" ];
      verbs = [
        "create"
        "patch"
      ];
    }
  ];

  serviceAccountName = "rerun-operator";
in
{
  options.rerun-operator = {
    enable = lib.mkEnableOption "rerun-operator — Kubernetes operator for Rerun dashboards";

    namespace = lib.mkOption {
      type = lib.types.str;
      default = "rerun-operator";
      description = "Namespace the operator runs in.";
    };

    createNamespace = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Whether this module should declare the operator namespace.";
    };

    image = lib.mkOption {
      type = lib.types.str;
      default = "us-west1-docker.pkg.dev/casazza-identity/nixlab/rerun-operator:latest";
      description = "Container image for the operator.";
    };

    imagePullSecrets = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "gar-pull-secret" ];
      description = ''
        Names of imagePullSecrets in the operator's namespace.
        The secret(s) must exist in `namespace` — pull secrets are
        namespaced, so a separate copy is required from whatever
        exists in e.g. `hpc`.
      '';
    };

    replicas = lib.mkOption {
      type = lib.types.int;
      default = 1;
      description = "Operator replica count (leader election not yet implemented).";
    };

    installCrds = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = ''
        Whether to install the RerunDashboard CRD. Uses a minimal shell
        with x-kubernetes-preserve-unknown-fields on .spec/.status. Set
        to false if you apply the real CRD (from `rerun-operator
        export-crds`) out-of-band.
      '';
    };

    metricsPort = lib.mkOption {
      type = lib.types.int;
      default = 8080;
      description = "HTTP port the operator exposes metrics + healthz on.";
    };

    logLevel = lib.mkOption {
      type = lib.types.str;
      default = "info,rerun_operator=debug";
      description = "RUST_LOG value for the operator process.";
    };

    resources = lib.mkOption {
      type = lib.types.attrs;
      default = {
        requests = {
          cpu = "100m";
          memory = "128Mi";
        };
        limits = {
          cpu = "500m";
          memory = "512Mi";
        };
      };
      description = "Pod resource requests/limits for the operator.";
    };
  };

  config = lib.mkIf cfg.enable {
    kubernetes.objects =
      lib.optional cfg.createNamespace {
        apiVersion = "v1";
        kind = "Namespace";
        metadata = {
          name = cfg.namespace;
          inherit labels;
        };
      }
      ++ lib.optional cfg.installCrds rerunDashboardCrd
      ++ [
        # ServiceAccount
        {
          apiVersion = "v1";
          kind = "ServiceAccount";
          metadata = {
            name = serviceAccountName;
            namespace = cfg.namespace;
            inherit labels;
          };
        }

        # ClusterRole
        {
          apiVersion = "rbac.authorization.k8s.io/v1";
          kind = "ClusterRole";
          metadata = {
            name = "rerun-operator";
            inherit labels;
          };
          rules = clusterRoleRules;
        }

        # ClusterRoleBinding
        {
          apiVersion = "rbac.authorization.k8s.io/v1";
          kind = "ClusterRoleBinding";
          metadata = {
            name = "rerun-operator";
            inherit labels;
          };
          roleRef = {
            apiGroup = "rbac.authorization.k8s.io";
            kind = "ClusterRole";
            name = "rerun-operator";
          };
          subjects = [
            {
              kind = "ServiceAccount";
              name = serviceAccountName;
              namespace = cfg.namespace;
            }
          ];
        }

        # Deployment
        {
          apiVersion = "apps/v1";
          kind = "Deployment";
          metadata = {
            name = "rerun-operator";
            namespace = cfg.namespace;
            inherit labels;
          };
          spec = {
            replicas = cfg.replicas;
            selector.matchLabels = labels;
            template = {
              metadata.labels = labels;
              spec = {
                serviceAccountName = serviceAccountName;
                imagePullSecrets = map (n: { name = n; }) cfg.imagePullSecrets;
                containers = [
                  {
                    name = "rerun-operator";
                    image = cfg.image;
                    # Always for the :latest tag during early development;
                    # switch to IfNotPresent once the image is tagged by SHA
                    # and the manifest pins an immutable reference.
                    imagePullPolicy = "Always";
                    # The operator binary takes no subcommand to run the
                    # controller loop — only `export-crds` is a real
                    # subcommand. See crates/rerun-operator/src/main.rs.
                    env = [
                      {
                        name = "RUST_LOG";
                        value = cfg.logLevel;
                      }
                      {
                        name = "METRICS_PORT";
                        value = toString cfg.metricsPort;
                      }
                      {
                        name = "OPERATOR_NAMESPACE";
                        valueFrom.fieldRef.fieldPath = "metadata.namespace";
                      }
                    ];
                    ports = [
                      {
                        name = "metrics";
                        containerPort = cfg.metricsPort;
                        protocol = "TCP";
                      }
                    ];
                    readinessProbe = {
                      httpGet = {
                        path = "/healthz";
                        port = "metrics";
                      };
                      initialDelaySeconds = 5;
                      periodSeconds = 10;
                    };
                    livenessProbe = {
                      httpGet = {
                        path = "/healthz";
                        port = "metrics";
                      };
                      initialDelaySeconds = 15;
                      periodSeconds = 20;
                    };
                    resources = cfg.resources;
                    securityContext = {
                      allowPrivilegeEscalation = false;
                      readOnlyRootFilesystem = true;
                      runAsNonRoot = true;
                      runAsUser = 65532;
                      capabilities.drop = [ "ALL" ];
                    };
                  }
                ];
                securityContext = {
                  runAsNonRoot = true;
                  seccompProfile.type = "RuntimeDefault";
                };
              };
            };
          };
        }

        # Service for metrics + healthz
        {
          apiVersion = "v1";
          kind = "Service";
          metadata = {
            name = "rerun-operator-metrics";
            namespace = cfg.namespace;
            inherit labels;
          };
          spec = {
            type = "ClusterIP";
            selector = labels;
            ports = [
              {
                name = "metrics";
                port = cfg.metricsPort;
                targetPort = "metrics";
                protocol = "TCP";
              }
            ];
          };
        }
      ];
  };
}
