//! Render a RerunDashboard blueprint into the Python source the viewer pod
//! executes at startup.
//!
//! Output structure:
//! - imports `rerun as rr`, `rerun.blueprint as rrb`
//! - exposes a module-level `bp` variable holding the rendered `rrb.Blueprint`
//! - exposes a `run()` function that boots `rr.serve_web` with the blueprint
//!
//! The viewer container's command runs `python -u -c "import blueprint; blueprint.run()"`.

use rerun_operator_api::v1alpha1::{
    Blueprint, Container, GridContainer, IngestConfig, LeafView, RerunDashboardSpec, View,
};
use std::fmt::Write;

pub struct RenderedBlueprint {
    /// Contents of `blueprint.py`.
    pub python: String,
}

/// Render the blueprint + serve_web bootstrap into a single Python module.
pub fn render(
    application_id: &str,
    spec: &RerunDashboardSpec,
) -> RenderedBlueprint {
    let mut out = String::new();
    out.push_str("# Auto-generated by rerun-operator. Do not edit.\n");
    out.push_str("import time\n");
    out.push_str("import rerun as rr\n");
    out.push_str("import rerun.blueprint as rrb\n\n");

    out.push_str("bp = ");
    render_blueprint(&mut out, &spec.blueprint);
    out.push_str("\n\n");

    render_run_fn(&mut out, application_id, &spec.ingest);
    out.push_str("\n\nif __name__ == \"__main__\":\n    run()\n");

    RenderedBlueprint { python: out }
}

fn render_blueprint(out: &mut String, bp: &Blueprint) {
    out.push_str("rrb.Blueprint(\n    ");
    render_view(out, &bp.root, 1);
    writeln!(out, ",").unwrap();
    writeln!(
        out,
        "    collapse_panels={},",
        py_bool(bp.collapse_panels)
    )
    .unwrap();
    out.push(')');
}

fn render_view(out: &mut String, view: &View, indent: usize) {
    let pad = "    ".repeat(indent);
    match view {
        View::Horizontal(c) => {
            out.push_str("rrb.Horizontal(\n");
            render_container(out, c, indent + 1, "column_shares");
            write!(out, "{pad})").unwrap();
        }
        View::Vertical(c) => {
            out.push_str("rrb.Vertical(\n");
            render_container(out, c, indent + 1, "row_shares");
            write!(out, "{pad})").unwrap();
        }
        View::Grid(g) => {
            out.push_str("rrb.Grid(\n");
            render_grid(out, g, indent + 1);
            write!(out, "{pad})").unwrap();
        }
        View::Spatial3D(l) => render_leaf(out, "Spatial3DView", l),
        View::Spatial2D(l) => render_leaf(out, "Spatial2DView", l),
        View::TimeSeries(l) => render_leaf(out, "TimeSeriesView", l),
        View::TextLog(l) => render_leaf(out, "TextLogView", l),
        View::BarChart(l) => render_leaf(out, "BarChartView", l),
    }
}

fn render_container(out: &mut String, c: &Container, indent: usize, shares_kw: &str) {
    let pad = "    ".repeat(indent);
    for child in &c.children {
        write!(out, "{pad}").unwrap();
        render_view(out, child, indent);
        writeln!(out, ",").unwrap();
    }
    if !c.shares.is_empty() {
        let shares: Vec<String> = c.shares.iter().map(|s| s.to_string()).collect();
        writeln!(out, "{pad}{shares_kw}=[{}],", shares.join(", ")).unwrap();
    }
    if let Some(name) = &c.name {
        writeln!(out, "{pad}name={},", py_str(name)).unwrap();
    }
}

fn render_grid(out: &mut String, g: &GridContainer, indent: usize) {
    let pad = "    ".repeat(indent);
    for child in &g.children {
        write!(out, "{pad}").unwrap();
        render_view(out, child, indent);
        writeln!(out, ",").unwrap();
    }
    writeln!(out, "{pad}grid_columns={},", g.columns).unwrap();
    if let Some(name) = &g.name {
        writeln!(out, "{pad}name={},", py_str(name)).unwrap();
    }
}

fn render_leaf(out: &mut String, view_ty: &str, l: &LeafView) {
    write!(out, "rrb.{view_ty}(origin={}", py_str(&l.origin)).unwrap();
    if !l.contents.is_empty() {
        let items: Vec<String> = l.contents.iter().map(|s| py_str(s)).collect();
        write!(out, ", contents=[{}]", items.join(", ")).unwrap();
    }
    if let Some(name) = &l.name {
        write!(out, ", name={}", py_str(name)).unwrap();
    }
    out.push(')');
}

fn render_run_fn(out: &mut String, application_id: &str, ingest: &IngestConfig) {
    writeln!(out, "def run():").unwrap();
    writeln!(out, "    rr.init({}, default_blueprint=bp)", py_str(application_id)).unwrap();
    writeln!(
        out,
        "    rr.serve_web(open_browser=False, web_port={}, ws_port={}, default_blueprint=bp)",
        ingest.web_port, ingest.port
    )
    .unwrap();
    writeln!(out, "    rr.send_blueprint(bp, make_active=True, make_default=True)").unwrap();
    writeln!(
        out,
        "    print(\"rerun viewer ready: web={}, ws={}\", flush=True)",
        ingest.web_port, ingest.port
    )
    .unwrap();
    writeln!(out, "    while True:").unwrap();
    writeln!(out, "        time.sleep(60)").unwrap();
}

fn py_str(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn py_bool(b: bool) -> &'static str {
    if b { "True" } else { "False" }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rerun_operator_api::v1alpha1::{
        Blueprint, Container, IngestConfig, IngestProtocol, IngressConfig, LeafView,
        RerunDashboardSpec, StorageConfig, View, Visibility,
    };

    fn minimal_spec() -> RerunDashboardSpec {
        RerunDashboardSpec {
            rerun_version: "0.22.1".into(),
            application_id: Some("spot".into()),
            blueprint: Blueprint {
                collapse_panels: true,
                root: View::Horizontal(Container {
                    children: vec![
                        View::Spatial3D(LeafView {
                            origin: "/".into(),
                            contents: vec!["+/**".into()],
                            name: Some("Robot".into()),
                        }),
                        View::TimeSeries(LeafView {
                            origin: "/metrics".into(),
                            contents: vec![],
                            name: None,
                        }),
                    ],
                    shares: vec![3, 1],
                    name: None,
                }),
            },
            ingest: IngestConfig {
                protocol: IngestProtocol::Tcp,
                port: 9877,
                web_port: 9090,
                memory_limit: None,
            },
            storage: StorageConfig::default(),
            retention_seconds: None,
            ingress: IngressConfig {
                visibility: Visibility::Cluster,
                ..Default::default()
            },
            resources: None,
        }
    }

    #[test]
    fn renders_horizontal_with_shares() {
        let py = render("spot", &minimal_spec()).python;
        assert!(py.contains("rrb.Blueprint("));
        assert!(py.contains("rrb.Horizontal("));
        assert!(py.contains("rrb.Spatial3DView(origin=\"/\""));
        assert!(py.contains("rrb.TimeSeriesView(origin=\"/metrics\""));
        assert!(py.contains("column_shares=[3, 1]"));
        assert!(py.contains("collapse_panels=True"));
    }

    #[test]
    fn renders_run_fn_with_ports() {
        let py = render("spot", &minimal_spec()).python;
        assert!(py.contains("def run():"));
        assert!(py.contains("rr.init(\"spot\""));
        assert!(py.contains("web_port=9090"));
        assert!(py.contains("ws_port=9877"));
        assert!(py.contains("make_active=True"));
    }

    #[test]
    fn emits_leaf_contents_filter() {
        let py = render("spot", &minimal_spec()).python;
        assert!(py.contains("contents=[\"+/**\"]"));
    }

    #[test]
    fn escapes_quotes_in_strings() {
        let mut spec = minimal_spec();
        spec.application_id = Some("spot\"evil".into());
        let py = render("spot\"evil", &spec).python;
        assert!(py.contains("rr.init(\"spot\\\"evil\""));
    }
}
