//! Render a RerunDashboard blueprint into the shell command its viewer pod
//! executes at startup.
//!
//! The viewer container is a vanilla `python:<ver>-slim` image; we install
//! `rerun-sdk==<spec.rerunVersion>` at boot and either:
//!
//! - run a generated Python module that pushes a structured blueprint and
//!   serves the gRPC + web ports (`LiveStream` / `Mixed`), or
//! - exec the `rerun` CLI with positional `.rrd` / `.rbl` files
//!   (`FileReplay`).
//!
//! Everything below is shell-command-shaped — `RenderedLaunch` carries either
//! the inline Python source (for the Python launch path) or a list of CLI
//! tokens (for the `rerun` CLI launch path), plus the final `sh -c` command
//! the container should run.

use rerun_operator_api::v1alpha1::{
    Blueprint, Container, DataSourceKind, GridContainer, LeafView, LiveStreamConfig,
    RerunDashboardSpec, View, WireTransport, resolve_live_port,
};
use std::fmt::Write;

/// Rendered launch artifacts for the viewer pod.
pub struct RenderedLaunch {
    /// Optional Python module source (`blueprint.py`) — None for FileReplay.
    pub python: Option<String>,
    /// Final shell command (the container's `sh -c <cmd>`).
    pub shell: String,
    /// Resolved live ingest port (when applicable).
    pub live_port: Option<u16>,
    /// Resolved web UI port (None when web is disabled).
    pub web_port: Option<u16>,
    /// Resolved transport for the live stream — used by tests and any future
    /// caller wanting to surface the wire protocol on a status field. Kept
    /// here so the reconciler does not have to reproduce the resolution
    /// logic if it ever needs the transport.
    #[allow(dead_code)]
    pub transport: Option<WireTransport>,
}

/// Default file-replay mount path inside the viewer pod.
pub const DEFAULT_REPLAY_MOUNT: &str = "/var/lib/rerun/recordings";

/// Render the launch artifacts for a dashboard.
///
/// `LiveStream` and `Mixed` produce a Python module that is dropped in via a
/// ConfigMap and `python -u`'d. `FileReplay` shells out to `rerun` with the
/// resolved `.rrd` / `.rbl` paths.
pub fn render(application_id: &str, spec: &RerunDashboardSpec) -> RenderedLaunch {
    match spec.data_source.kind {
        DataSourceKind::FileReplay => render_file_replay(spec),
        // Mixed: launch the Python script (which can `rr.log_file_from_path`
        // on startup if extended). For now treat Mixed as LiveStream and let
        // operators load files into the running viewer manually.
        // TODO(mixed): emit `rr.log_file_from_path()` calls for the resolved
        // file globs at boot.
        DataSourceKind::LiveStream | DataSourceKind::Mixed => {
            render_live_stream(application_id, spec)
        }
    }
}

// -----------------------------------------------------------------------------
// LiveStream / Mixed
// -----------------------------------------------------------------------------

fn render_live_stream(application_id: &str, spec: &RerunDashboardSpec) -> RenderedLaunch {
    let live = effective_live_config(spec.data_source.live.as_ref());
    let transport = live.transport;
    let live_port = live
        .port
        .unwrap_or_else(|| resolve_live_port(&spec.rerun_version, transport));
    let web_port = effective_web_port(spec);

    let mut out = String::new();
    out.push_str("# Auto-generated by rerun-operator. Do not edit.\n");
    out.push_str("import time\n");
    out.push_str("import rerun as rr\n");
    out.push_str("import rerun.blueprint as rrb\n\n");

    out.push_str("bp = ");
    render_blueprint(&mut out, &spec.blueprint);
    out.push_str("\n\n");

    render_run_fn(
        &mut out,
        application_id,
        transport,
        live_port,
        web_port,
        live.memory_limit.as_deref(),
    );
    out.push_str("\n\nif __name__ == \"__main__\":\n    run()\n");

    let version = &spec.rerun_version;
    let shell = format!(
        "pip install --no-cache-dir --quiet 'rerun-sdk=={version}' && \
         exec python -u /opt/rerun/blueprint/blueprint.py"
    );

    RenderedLaunch {
        python: Some(out),
        shell,
        live_port: Some(live_port),
        web_port,
        transport: Some(transport),
    }
}

fn effective_live_config(live: Option<&LiveStreamConfig>) -> LiveStreamConfig {
    live.cloned().unwrap_or_default()
}

fn effective_web_port(spec: &RerunDashboardSpec) -> Option<u16> {
    if !spec.presentation.web {
        return None;
    }
    Some(
        spec.presentation
            .web_port
            .unwrap_or(rerun_operator_api::v1alpha1::DEFAULT_WEB_PORT),
    )
}

fn render_blueprint(out: &mut String, bp: &Blueprint) {
    out.push_str("rrb.Blueprint(\n    ");
    render_view(out, &bp.root, 1);
    writeln!(out, ",").unwrap();
    writeln!(out, "    collapse_panels={},", py_bool(bp.collapse_panels)).unwrap();
    out.push(')');
}

fn render_view(out: &mut String, view: &View, indent: usize) {
    let pad = "    ".repeat(indent);
    match view {
        View::Horizontal(c) => {
            out.push_str("rrb.Horizontal(\n");
            render_container(out, c, indent + 1, "column_shares");
            write!(out, "{pad})").unwrap();
        }
        View::Vertical(c) => {
            out.push_str("rrb.Vertical(\n");
            render_container(out, c, indent + 1, "row_shares");
            write!(out, "{pad})").unwrap();
        }
        View::Grid(g) => {
            out.push_str("rrb.Grid(\n");
            render_grid(out, g, indent + 1);
            write!(out, "{pad})").unwrap();
        }
        View::Spatial3D(l) => render_leaf(out, "Spatial3DView", l),
        View::Spatial2D(l) => render_leaf(out, "Spatial2DView", l),
        View::TimeSeries(l) => render_leaf(out, "TimeSeriesView", l),
        View::TextLog(l) => render_leaf(out, "TextLogView", l),
        View::BarChart(l) => render_leaf(out, "BarChartView", l),
    }
}

fn render_container(out: &mut String, c: &Container, indent: usize, shares_kw: &str) {
    let pad = "    ".repeat(indent);
    for child in &c.children {
        write!(out, "{pad}").unwrap();
        render_view(out, child, indent);
        writeln!(out, ",").unwrap();
    }
    if !c.shares.is_empty() {
        let shares: Vec<String> = c.shares.iter().map(|s| s.to_string()).collect();
        writeln!(out, "{pad}{shares_kw}=[{}],", shares.join(", ")).unwrap();
    }
    if let Some(name) = &c.name {
        writeln!(out, "{pad}name={},", py_str(name)).unwrap();
    }
}

fn render_grid(out: &mut String, g: &GridContainer, indent: usize) {
    let pad = "    ".repeat(indent);
    for child in &g.children {
        write!(out, "{pad}").unwrap();
        render_view(out, child, indent);
        writeln!(out, ",").unwrap();
    }
    writeln!(out, "{pad}grid_columns={},", g.columns).unwrap();
    if let Some(name) = &g.name {
        writeln!(out, "{pad}name={},", py_str(name)).unwrap();
    }
}

fn render_leaf(out: &mut String, view_ty: &str, l: &LeafView) {
    write!(out, "rrb.{view_ty}(origin={}", py_str(&l.origin)).unwrap();
    if !l.contents.is_empty() {
        let items: Vec<String> = l.contents.iter().map(|s| py_str(s)).collect();
        write!(out, ", contents=[{}]", items.join(", ")).unwrap();
    }
    if let Some(name) = &l.name {
        write!(out, ", name={}", py_str(name)).unwrap();
    }
    out.push(')');
}

fn render_run_fn(
    out: &mut String,
    application_id: &str,
    transport: WireTransport,
    live_port: u16,
    web_port: Option<u16>,
    memory_limit: Option<&str>,
) {
    writeln!(out, "def run():").unwrap();
    writeln!(
        out,
        "    rr.init({}, default_blueprint=bp)",
        py_str(application_id)
    )
    .unwrap();

    match transport {
        WireTransport::Grpc => {
            // 0.23+ API. `serve_grpc` opens the gRPC ingest port; the optional
            // `serve_web_viewer` serves the static HTML/JS bundle. Both are
            // called from the viewer process — the loggers connect over gRPC.
            let mem = py_opt_str(memory_limit);
            writeln!(
                out,
                "    rr.serve_grpc(grpc_port={live_port}, server_memory_limit={mem})"
            )
            .unwrap();
            if let Some(wp) = web_port {
                writeln!(
                    out,
                    "    rr.serve_web_viewer(web_port={wp}, open_browser=False, \
                     connect_to=\"rerun+http://127.0.0.1:{live_port}/proxy\")"
                )
                .unwrap();
            }
            writeln!(out, "    rr.send_blueprint(bp, make_active=True, make_default=True)")
                .unwrap();
            if let Some(wp) = web_port {
                writeln!(
                    out,
                    "    print(\"rerun viewer ready: web={wp}, grpc={live_port}\", flush=True)"
                )
                .unwrap();
            } else {
                writeln!(
                    out,
                    "    print(\"rerun viewer ready: grpc={live_port}\", flush=True)"
                )
                .unwrap();
            }
        }
        WireTransport::WebSocket => {
            // Legacy 0.22.x API. `serve_web` doubles as the WebSocket ingest
            // server (`ws_port`) and the static web bundle (`web_port`).
            let wp = web_port.unwrap_or(rerun_operator_api::v1alpha1::DEFAULT_WEB_PORT);
            let mem = py_opt_str(memory_limit);
            writeln!(
                out,
                "    rr.serve_web(open_browser=False, web_port={wp}, ws_port={live_port}, \
                 default_blueprint=bp, server_memory_limit={mem})"
            )
            .unwrap();
            writeln!(out, "    rr.send_blueprint(bp, make_active=True, make_default=True)")
                .unwrap();
            writeln!(
                out,
                "    print(\"rerun viewer ready: web={wp}, ws={live_port}\", flush=True)"
            )
            .unwrap();
        }
    }

    writeln!(out, "    while True:").unwrap();
    writeln!(out, "        time.sleep(60)").unwrap();
}

// -----------------------------------------------------------------------------
// FileReplay
// -----------------------------------------------------------------------------

fn render_file_replay(spec: &RerunDashboardSpec) -> RenderedLaunch {
    let files = spec
        .data_source
        .files
        .as_ref()
        .expect("FileReplay DataSource must populate `files`");
    let mount = files
        .mount_path
        .as_deref()
        .unwrap_or(DEFAULT_REPLAY_MOUNT);
    let globs: Vec<&str> = if files.globs.is_empty() {
        vec!["*.rrd"]
    } else {
        files.globs.iter().map(String::as_str).collect()
    };

    let live = effective_live_config(spec.data_source.live.as_ref());
    let live_port = live
        .port
        .unwrap_or_else(|| resolve_live_port(&spec.rerun_version, live.transport));
    let web_port = effective_web_port(spec);
    let version = &spec.rerun_version;

    // CLI: `rerun --serve-web --bind :: --port <grpc> --web-viewer-port <web>
    //         <expanded paths>`. Expansion happens via `sh -c` glob expansion;
    // we cd into the mount so user-supplied globs are relative.
    let mut tokens: Vec<String> = vec![
        "rerun".to_string(),
        "--serve-web".to_string(),
        "--bind".to_string(),
        "::".to_string(),
        "--port".to_string(),
        live_port.to_string(),
    ];
    if let Some(wp) = web_port {
        tokens.push("--web-viewer-port".to_string());
        tokens.push(wp.to_string());
    }
    if let Some(limit) = &live.memory_limit {
        tokens.push("--server-memory-limit".to_string());
        tokens.push(limit.clone());
    }
    // Glob args appended last, kept unquoted in the rendered shell so the
    // shell expands them at runtime.
    let cmd_prefix = tokens.join(" ");
    let glob_args = globs.join(" ");
    let shell = format!(
        "pip install --no-cache-dir --quiet 'rerun-sdk=={version}' && cd {mount} && \
         exec {cmd_prefix} {glob_args}"
    );

    RenderedLaunch {
        python: None,
        shell,
        live_port: Some(live_port),
        web_port,
        transport: Some(live.transport),
    }
}

// -----------------------------------------------------------------------------
// helpers
// -----------------------------------------------------------------------------

fn py_str(s: &str) -> String {
    let escaped = s.replace('\\', "\\\\").replace('"', "\\\"");
    format!("\"{escaped}\"")
}

fn py_bool(b: bool) -> &'static str {
    if b { "True" } else { "False" }
}

fn py_opt_str(s: Option<&str>) -> String {
    match s {
        Some(s) => py_str(s),
        None => "None".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rerun_operator_api::v1alpha1::{
        Blueprint, Container, DataSource, DataSourceKind, FileReplayConfig, IngressConfig,
        LeafView, LiveStreamConfig, Presentation, RerunDashboardSpec, View, Visibility,
        WireTransport,
    };

    fn live_stream_spec() -> RerunDashboardSpec {
        RerunDashboardSpec {
            rerun_version: "0.31.3".into(),
            application_id: Some("spot".into()),
            blueprint: Blueprint {
                collapse_panels: true,
                root: View::Horizontal(Container {
                    children: vec![
                        View::Spatial3D(LeafView {
                            origin: "/".into(),
                            contents: vec!["+/**".into()],
                            name: Some("Robot".into()),
                        }),
                        View::TimeSeries(LeafView {
                            origin: "/metrics".into(),
                            contents: vec![],
                            name: None,
                        }),
                    ],
                    shares: vec![3, 1],
                    name: None,
                }),
            },
            data_source: DataSource {
                kind: DataSourceKind::LiveStream,
                live: Some(LiveStreamConfig {
                    transport: WireTransport::Grpc,
                    port: None,
                    memory_limit: None,
                }),
                files: None,
            },
            presentation: Presentation {
                web: true,
                web_port: None,
                ingress: IngressConfig {
                    visibility: Visibility::Cluster,
                    ..Default::default()
                },
            },
            resources: None,
        }
    }

    #[test]
    fn renders_horizontal_with_shares() {
        let r = render("spot", &live_stream_spec());
        let py = r.python.expect("python source for LiveStream");
        assert!(py.contains("rrb.Blueprint("));
        assert!(py.contains("rrb.Horizontal("));
        assert!(py.contains("rrb.Spatial3DView(origin=\"/\""));
        assert!(py.contains("rrb.TimeSeriesView(origin=\"/metrics\""));
        assert!(py.contains("column_shares=[3, 1]"));
        assert!(py.contains("collapse_panels=True"));
    }

    #[test]
    fn renders_run_fn_with_ports() {
        let r = render("spot", &live_stream_spec());
        let py = r.python.expect("python source for LiveStream");
        assert!(py.contains("def run():"));
        assert!(py.contains("rr.init(\"spot\""));
        // 0.31.3 + Grpc → gRPC port 9876 / web port 9090.
        assert!(py.contains("rr.serve_grpc(grpc_port=9876"));
        assert!(py.contains("rr.serve_web_viewer(web_port=9090"));
        assert!(py.contains("make_active=True"));
        assert_eq!(r.live_port, Some(9876));
        assert_eq!(r.web_port, Some(9090));
        assert_eq!(r.transport, Some(WireTransport::Grpc));
    }

    #[test]
    fn renders_legacy_websocket() {
        let mut spec = live_stream_spec();
        spec.rerun_version = "0.22.1".into();
        spec.data_source.live = Some(LiveStreamConfig {
            transport: WireTransport::WebSocket,
            port: None,
            memory_limit: Some("25%".into()),
        });
        let r = render("spot", &spec);
        let py = r.python.expect("python source");
        assert!(py.contains("rr.serve_web(open_browser=False"));
        assert!(py.contains("ws_port=9877"));
        assert!(py.contains("web_port=9090"));
        assert!(py.contains("server_memory_limit=\"25%\""));
        assert_eq!(r.live_port, Some(9877));
        assert_eq!(r.transport, Some(WireTransport::WebSocket));
    }

    #[test]
    fn emits_leaf_contents_filter() {
        let r = render("spot", &live_stream_spec());
        let py = r.python.expect("python source");
        assert!(py.contains("contents=[\"+/**\"]"));
    }

    #[test]
    fn escapes_quotes_in_strings() {
        let mut spec = live_stream_spec();
        spec.application_id = Some("spot\"evil".into());
        let r = render("spot\"evil", &spec);
        let py = r.python.expect("python source");
        assert!(py.contains("rr.init(\"spot\\\"evil\""));
    }

    #[test]
    fn live_stream_shell_installs_sdk_and_runs_python() {
        let r = render("spot", &live_stream_spec());
        assert!(r.shell.contains("pip install"));
        assert!(r.shell.contains("rerun-sdk==0.31.3"));
        assert!(r.shell.contains("python -u /opt/rerun/blueprint/blueprint.py"));
    }

    #[test]
    fn file_replay_emits_cli_invocation() {
        let mut spec = live_stream_spec();
        spec.data_source = DataSource {
            kind: DataSourceKind::FileReplay,
            live: None,
            files: Some(FileReplayConfig {
                pvc: "training-recordings".into(),
                globs: vec![],
                mount_path: None,
                file_retention_seconds: None,
            }),
        };
        let r = render("spot", &spec);
        assert!(r.python.is_none());
        assert!(r.shell.contains("pip install"));
        assert!(r.shell.contains("rerun-sdk==0.31.3"));
        assert!(r.shell.contains("cd /var/lib/rerun/recordings"));
        assert!(r.shell.contains("rerun --serve-web --bind :: --port 9876"));
        assert!(r.shell.contains("--web-viewer-port 9090"));
        assert!(r.shell.contains("*.rrd"));
        assert_eq!(r.live_port, Some(9876));
    }

    #[test]
    fn file_replay_honors_custom_globs_and_mount() {
        let mut spec = live_stream_spec();
        spec.data_source = DataSource {
            kind: DataSourceKind::FileReplay,
            live: None,
            files: Some(FileReplayConfig {
                pvc: "rrds".into(),
                globs: vec!["session-*.rrd".into(), "blueprint.rbl".into()],
                mount_path: Some("/data/rrds".into()),
                file_retention_seconds: None,
            }),
        };
        let r = render("spot", &spec);
        assert!(r.shell.contains("cd /data/rrds"));
        assert!(r.shell.contains("session-*.rrd blueprint.rbl"));
    }

    #[test]
    fn presentation_disables_web_when_false() {
        let mut spec = live_stream_spec();
        spec.presentation.web = false;
        let r = render("spot", &spec);
        let py = r.python.expect("python source");
        assert!(!py.contains("rr.serve_web_viewer"));
        assert_eq!(r.web_port, None);
    }
}
